services:
  climweb-backup-rclone:
    restart: always
    build:
      context: ./rclone
      dockerfile: Dockerfile
    container_name: climweb-backup-rclone
    env_file: .env
    volumes:
      - ${BACKUP_DIR}:/backup
      - ./rclone/config:/root/.config/rclone

  climweb-backup-rsync:
    restart: always
    build:
      context: ./rsync
      dockerfile: Dockerfile
    container_name: climweb-backup-rsync
    env_file: .env
    volumes:
      - ${BACKUP_DIR}:/backup
      - ./rclone/config:/root/.config/rclone
      - ~/.ssh:/root/.ssh:ro
      # - ${SSH_KEY_PATH}:/root/ssh:ro
